### PR TITLE
solved Javascript Palindrome algorithm

### PR DESCRIPTION
**Pull request by webdott**
Palindrome Algorithm solved #2

### CODE REVIEW

**Comment by i4gfuta-admin** [comment]
Good : )

**Comment by webdott** [comment]
> Good : )

Hello 🙂, my hacktoberfest status is still saying ineligible pr. Does the repo have the hacktoberfest topic?

**Comment by akojif** [comment]
Yeah, It has.

**Comment by i4gfuta-admin** [comment]
@caspero-62 Check your dashboard now, it should be effective.

**Comment by webdott** [comment]
> @caspero-62 Check your dashboard now, it should be effective. 

Thanks a lot. It is now effective

**Comment by webdott** [comment]
> Yeah, It has. 

Thanks for the reply. It is now effective

**Pull request merged**
