### PR TITLE
Javascript Implementation of Fibonacci Series

### PR DESCRIPTION
**Pull request by GerardoUbuntu**
Added implementation of Fibonacci series in JavaScript

### CODE REVIEW

**Review by Humiditii — APPROVED** [review]

**Review by i4gfuta-admin — COMMENTED** [review]
Please change the code, the function is supposed to return sequence of numbers, but yours isn't

**Review by i4gfuta-admin — COMMENTED** [review]
This is not returning fibonacci sequence.

**Comment by GerardoUbuntu** [comment]
@i4gfuta-admin  Already changed the code to return a Fibonacci sequence

**Comment by i4gfuta-admin** [comment]
@GerardoUbuntu Kindly rename your file to something else maybe fibonacci-2.js, as there's a file name fibonacci.js already.
Do this to avoid conflicts

**Comment by GerardoUbuntu** [comment]
@i4gfuta-admin  I changed the filename from fibonacci.js to fibonacci-2.js

**Pull request merged**
